### PR TITLE
Adds fills websocket feed

### PR DESCRIPTION
**Pull request by hoakbuilds**
| Status  | Type  | ⚠️ Core Change | Issue |
| :---: | :---: | :---: | :--: |
| Hold | Feature | No | #95  |

## Problem

_What problem are you trying to solve?_

Latency issues between fills and events getting cranked + notification through RPC
Accounting for proper wallet balance etc

## Solution

_How did you solve the problem?_

Added the [fills websocket feed](https://docs.mango.markets/development-resources/client-libraries/fills-websocket-feed) which is considerably faster to push fill events than the streaming RPC

### CODE REVIEW

**Comment by sircrusher** [comment]
This looks good, just wondering if it should be in the Historical namespace/project. This is an alternate to the RPC events feed so not necessarily historical.

**Comment by murlokito** [comment]
> This looks good, just wondering if it should be in the Historical namespace/project. This is an alternate to the RPC events feed so not necessarily historical.

I thought about the same thing, but it doesn't make much sense to be in the other project either considering it's just the Mango Program and the structures used to decode with data from the RPC. OTOH the "Historical" project doesn't just contain historical data since you can get the volume and stuff from the other APIs

**Comment by mschneider** [comment]
FillEvent is base64 encoded mango fill event. Can you decode it for the users?

**Comment by murlokito** [comment]
> FillEvent is base64 encoded mango fill event. Can you decode it for the users?

Yes, I could change it to return the `FillEvents` already decoded

**Pull request merged**
